import esbuild from 'esbuild';
import process from 'node:process';

const production = process.argv[2] === 'production';
const banner = '/* Generated by esbuild. Source: src/main.js */';

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.js'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr'
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  minify: production,
  sourcemap: production ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js'
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
