// Import the Ichimoku text palettes, then generate Obsidian appearance selectors.
// Run with a canonical themes.json path to refresh; --check verifies committed CSS.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.join(__dirname, '..');
const snapshotPath = path.join(root, 'src/theme-catalog.json');
const input = process.argv[2];
if (input && input !== '--check') {
  const bytes = fs.readFileSync(input);
  const family = JSON.parse(bytes).families.ichimoku;
  const snapshot = { source: 'Shared trading theme catalog, Ichimoku family', sourceSha256: crypto.createHash('sha256').update(bytes).digest('hex'), order: family.dropdownOrder.filter(name => name !== 'Custom'), aliases: family.aliases, themes: {} };
  for (const name of snapshot.order) {
    snapshot.themes[name] = { className: `yaml-properties-theme-${family.codes[name].java.toLowerCase().replaceAll('_', '-')}`, modes: {} };
    for (const mode of ['dark', 'light']) {
      const palette = family.themes[name].matrix[mode];
      snapshot.themes[name].modes[mode] = Object.fromEntries(['textBullish', 'textBearish', 'text'].map(role => [role, palette[role]]));
    }
  }
  fs.writeFileSync(snapshotPath, JSON.stringify(snapshot, null, 2) + '\n');
}
const catalog = JSON.parse(fs.readFileSync(snapshotPath));
const roles = { string: 'textBullish', number: 'textBearish', boolean: 'textBearish', null: 'text', anchor: 'textBullish', link: 'textBullish', date: 'textBearish', tag: 'textBearish' };
const start = '/* BEGIN SHARED THEME CATALOG — generated by scripts/sync-themes.cjs */';
const end = '/* END SHARED THEME CATALOG */';
const blocks = [start];
for (const name of catalog.order) {
  const theme = catalog.themes[name];
  blocks.push(`/* ${name} */`);
  for (const mode of ['dark', 'light']) {
    blocks.push(`body.theme-${mode}.${theme.className} {`);
    for (const [role, source] of Object.entries(roles)) blocks.push(`  --yaml-properties-${role}: ${theme.modes[mode][source]};`);
    blocks.push('}');
  }
}
blocks.push(end);
const cssPath = path.join(root, 'styles.css');
const css = fs.readFileSync(cssPath, 'utf8');
const first = css.indexOf(start), last = css.indexOf(end);
const generated = blocks.join('\n') + '\n';
const next = first < 0 ? css + '\n' + generated : css.slice(0, first) + generated + css.slice(last + end.length + 1);
if (input === '--check') {
  if (next !== css) throw new Error('Theme CSS is stale: run node scripts/sync-themes.cjs');
} else fs.writeFileSync(cssPath, next);
